version: "3"

services:
  app:
   
    image: amritpoudel/uploadhere:v1
    container_name: nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
      
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # environment:
    #  - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #  - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongo_data:
    driver: local
