apiVersion: apps/v1
kind: Deployment
metadata:
  name:  uploadhere-app
  namespace: default
  labels:
    app:  uploadhere-app
spec:
  selector:
    matchLabels:
      app: uploadhere-app
  replicas: 2
  template:
    metadata:
      labels:
        app:  uploadhere-app
    spec:
      serviceAccountName: uploadhere-serviceAccount
      containers:
      - name:  uploadhere
        image:  amritpoudel/uploadhere:v1
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_URI
        # - name: AWS_ACCESS_KEY_ID
        #   valueFrom:
        #     secretKeyRef:
        #       name : app-secrets
        #       key: AWS_ACCESS_KEY_ID

        # - name: AWS_SECRET_ACCESS_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: app-secrets
        #       key: AWS_SECRET_ACCESS_KEY

        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SESSION_SECRET

        ports:
        - containerPort:  3000
          name:  uploadhere-port
        